library(RColorBrewer)
team.colors<-c("#D22B45",
               "#99D22B",
               "#2BD2B8",
               "#642BD2",
               "#e1c558",
               "#d8c684",
               "#888336",
               "#819100",
               "#b2d26c",
               "#69a71e",
               "#b5cea4",
               "#3da735",
               "#508f48",
               "#0d992f",
               "#4dcb60",
               "#6ddc89",
               "#7fa185",
               "#02cf9b",
               "#7dd7be",
               "#02cab6",
               "#6dd3f1",
               "#008cb0",
               "#01bff5",
               "#2998ff",
               "#777dfa",
               "#b19dd5",
               "#997cd3")


master.colors<-c('ScRNA-seqAssay'=team.colors[1],
                 'BulkRNA-seqAssay'=team.colors[2],
                 'BulkRNA-seqAlignment'=team.colors[3],
                 'Demographics'=team.colors[4],
                 'Diagnosis'=team.colors[4],
                 'FamilyHistory'=team.colors[4],
                 'Exposure'=team.colors[4],
                 'FollowUp'=team.colors[4],
                 'Therapy'=team.colors[4],
                 'oriole'=team.colors[5],
                 'eagle'=team.colors[6],
                 'penguin'=team.colors[7],
                 'goose'=team.colors[8],
                 'auklet'=team.colors[9],
                 'cuckoo'=team.colors[10],
                 'parrot'=team.colors[11],
                 'ostrich'=team.colors[12],
                 'satinbirds'=team.colors[13],
                 'falcon'=team.colors[14],
                 'merlin'=team.colors[15],
                 'crane'=team.colors[16],
                 'hummingbird'=team.colors[17],
                 'pigeon'=team.colors[18],
                 'anhinga'=team.colors[19],
                 'bittern'=team.colors[20],
                 'egret'=team.colors[21],
                 'surfbird'=team.colors[22],
                 'swallow'=team.colors[23],
                 'heron'=team.colors[24],
                 'toucan'=team.colors[25],
                 'dove'=team.colors[26],
                 'owl'=team.colors[27],
                 'red'='#C21807',
                 'T'="#636363",
                 'F'="#F0F0F0",
                 'TRUE'="#636363",
                 'FALSE'="#F0F0F0", 
                 'gray'='#D3D3D3')



colScale <- scale_fill_manual(values = master.colors)
colScale_fill <- scale_fill_manual(values = master.colors)
colScale_color <- scale_color_manual(values = master.colors)